networks:
  lambda_net:
    driver: bridge

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    loki-retries: "2"
    loki-max-backoff: "800ms"
    loki-timeout: "1s"
    keep-file: "true"

services:
  # 1. PostgreSQL
  postgres:
    image: postgres:15
    container_name: taxi_postgres
    logging: *loki-logging
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: taxi_dwh
    ports:
      - "5432:5432"
    networks:
      - lambda_net

  # 2. ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: taxi_clickhouse
    logging: *loki-logging
    environment:
      CLICKHOUSE_USER: ${CH_USER}
      CLICKHOUSE_PASSWORD: ${CH_PASSWORD}
    ports:
      - "8123:8123" # HTTP port
      - "9090:9000" # Native port
    networks:
      - lambda_net

  # 3. MinIO
  minio:
    image: minio/minio:latest
    container_name: taxi_minio
    logging: *loki-logging
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # Web UI
    command: server /data --console-address ":9001"
    networks:
      - lambda_net

  # 4. Apache Kafka
  kafka:
    image: apache/kafka:3.7.0
    container_name: taxi_kafka
    logging: *loki-logging
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://taxi_kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@taxi_kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - lambda_net

  # 5. Apache Airflow + Spark
  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: taxi_airflow
    logging: *loki-logging
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: airflow standalone
    depends_on:
      postgres:
        condition: service_started
      init_infra:
        condition: service_completed_successfully
    networks:
      - lambda_net
    restart: always

  lake_writer:
    build:
      context: ./scripts/lake_writer
      dockerfile: Dockerfile
    container_name: taxi_lake_writer
    logging: *loki-logging
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=taxi_kafka:29092
      - MINIO_ENDPOINT=http://minio:9000
    depends_on:
      - kafka
      - minio
    networks:
      - lambda_net
    restart: always

  api_server:
    build:
      context: ./scripts/api_server
      dockerfile: Dockerfile
    container_name: taxi_api_server
    logging: *loki-logging
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=taxi_kafka:29092
    depends_on:
      - kafka
    networks:
      - lambda_net
    restart: always

  spark_streaming:
    build:
      context: ./scripts/spark_streaming
      dockerfile: Dockerfile
    container_name: taxi_spark_streaming
    logging: *loki-logging
    env_file:
      - .env
    environment:
      - KAFKA_BROKER=taxi_kafka:29092
      - CH_HOST=clickhouse
    depends_on:
      kafka:
        condition: service_started
      clickhouse:
        condition: service_started
      init_infra:
          condition: service_completed_successfully # Wait for init to finish
    networks:
      - lambda_net
    restart: always

  taxi_emulator:
    build:
      context: ./scripts/taxi_emulator
      dockerfile: Dockerfile
    container_name: taxi_emulator
    logging: *loki-logging
    environment:
      - API_URL=http://taxi_api_server:8000/api/v1/rides
    depends_on:
      - api_server
    networks:
      - lambda_net
    restart: always

  loki:
    image: grafana/loki:2.9.2
    container_name: pipeline_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - lambda_net
    restart: always

  grafana:
    image: grafana/grafana:10.2.2
    container_name: pipeline_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - lambda_net
    restart: always

  init_infra:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: taxi_init_infra
    env_file:
      - .env
    volumes:
      - ./scripts:/opt/airflow/scripts
    environment:
      - PYTHONPATH=/opt/airflow/scripts
    command: python /opt/airflow/scripts/init_db.py
    depends_on:
      postgres:
        condition: service_started
      clickhouse:
        condition: service_started
    networks:
      - lambda_net